/**:
  ros__parameters:
    object_low_velocity_thresh: 3.0 # if object velocity is lower than this value, adaptive cruise becomes disable.
    object_velocity_hysteresis_margin: 1.0 # hysteresis margin to change acc state for preventing chattering