name: sync-upstream

on:
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Print warning for invalid branch name
        if: ${{ github.event.inputs.target_branch  == 'tier4/main' }}
        run: |
            echo This action cannot be performed on 'tier/main' branch

      - name: Run sync-branches
        if: ${{ github.event.inputs.target_branch  != 'tier4/main' }}
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: ${{ inputs.target_branch }}
          sync-pr-branch: sync-upstream
          sync-target-repository: https://github.com/autowarefoundation/autoware.universe.git
          sync-target-branch: main
          pr-title: "chore: sync upstream"
          auto-merge-method: merge
